spring:
  datasource:
    url: jdbc:mysql://infernalwhaler.colbwtds2kha.eu-west-3.rds.amazonaws.com:3306/myblog
    username: root
    password: ExileNoir83
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: dev
      password: dev
      roles: ADMIN

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 5000